
import { GfxDevice } from "../gfx/platform/GfxPlatform.js";
import { SceneContext, SceneDesc, SceneGroup } from "../SceneBase.js";
import { SourceFileSystem, SourceLoadContext } from "./Main.js";
import { createScene } from "./Scenes.js";
import { createKitchenSinkSourceFilesytem } from "./Scenes_FileDrops.js";

import { CGESceneDesc } from "./Scenes_SourceDescs.js";

const id = 'CGE';
const name = 'zerozerozero';
const sceneDescs = [
    "MAIN MAPS",
    new CGESceneDesc('gm_xmasxmas', 'gm_xmasxmas', 'https://static.crowmonitor.com/download/maps/MAIN/gm_xmasxmas_cleaned.bsp'),
    new CGESceneDesc('city', 'city', 'https://static.crowmonitor.com/download/maps/MAIN/city.bsp'),
    new CGESceneDesc('city_discord', 'city (discord version)', 'https://static.crowmonitor.com/download/maps/MAIN/city_discord.bsp'),
    new CGESceneDesc('fuck', 'fuck', 'https://static.crowmonitor.com/download/maps/MAIN/fuck.bsp'),
    new CGESceneDesc('gravemap', 'gravemap', 'https://static.crowmonitor.com/download/maps/MAIN/gravemap.bsp'),
    "ODEJIT",
    new CGESceneDesc('odejit', 'ODEJIT', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit.bsp'),
    new CGESceneDesc('odejit2', 'ODEJIT2', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit2.bsp'),
    new CGESceneDesc('odejit3', 'ODEJIT3', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit3.bsp'),
    new CGESceneDesc('odejit4', 'ODEJIT4', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit4.bsp'),
    new CGESceneDesc('odejit5', 'ODEJIT5', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit5.bsp'),
    new CGESceneDesc('odejit6', 'ODEJIT6', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit6.bsp'),
    new CGESceneDesc('odejit7', 'ODEJIT7', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit7.bsp'),
    new CGESceneDesc('odejit8', 'ODEJIT8', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit8.bsp'),
    new CGESceneDesc('odejit9', 'ODEJIT9', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit9.bsp'),
    new CGESceneDesc('odejit10', 'ODEJIT10', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit10.bsp'),
    new CGESceneDesc('odejit11', 'ODEJIT11', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit11.bsp'),
    new CGESceneDesc('odejit12', 'ODEJIT12', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit12.bsp'),
    new CGESceneDesc('odejit13', 'ODEJIT13', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit13.bsp'),
    new CGESceneDesc('odejit14', 'ODEJIT14', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit14.bsp'),
    new CGESceneDesc('odejit15', 'ODEJIT15', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit15.bsp'),
    new CGESceneDesc('odejit16', 'ODEJIT16', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit16.bsp'),
    new CGESceneDesc('odejit17', 'ODEJIT17', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit17.bsp'),
    new CGESceneDesc('odejit18', 'ODEJIT18', 'https://static.crowmonitor.com/download/maps/ODEJIT/odejit18.bsp'),
    "GMAPPERS_PLAZA",
    new CGESceneDesc('gmappers_plaza', 'gmappers_plaza', 'https://static.crowmonitor.com/download/maps/GMAPPERSPLAZA/gmappers_plaza.bsp'),
    new CGESceneDesc('gmappers_plaza_v2', 'gmappers_plaza_v2', 'https://static.crowmonitor.com/download/maps/GMAPPERSPLAZA/gmappers_plaza_v2.bsp'),
    new CGESceneDesc('gmappers_plaza_v3', 'gmappers_plaza_v3', 'https://static.crowmonitor.com/download/maps/GMAPPERSPLAZA/gmappers_plaza_v3.bsp'),
    new CGESceneDesc('gmappers_plaza_v4', 'gmappers_plaza_v4', 'https://static.crowmonitor.com/download/maps/GMAPPERSPLAZA/gmappers_plaza_v4.bsp'),
    new CGESceneDesc('gmappers_christmas_plaza_v1', 'gmappers_christmas_plaza_v1', 'https://static.crowmonitor.com/download/maps/GMAPPERSPLAZA/gmappers_christmas_plaza_v1.bsp'),
    new CGESceneDesc('gmappers_christmas_plaza_v2', 'gmappers_christmas_plaza_v2', 'https://static.crowmonitor.com/download/maps/GMAPPERSPLAZA/gmappers_christmas_plaza_v2.bsp'),
    new CGESceneDesc('gmappers_christmas_plaza_v3', 'gmappers_christmas_plaza_v3', 'https://static.crowmonitor.com/download/maps/GMAPPERSPLAZA/gmappers_christmas_plaza_v3.bsp'),
    new CGESceneDesc('gmappers_christmas_plaza_v4', 'gmappers_christmas_plaza_v4', 'https://static.crowmonitor.com/download/maps/GMAPPERSPLAZA/gmappers_christmas_plaza_v4.bsp'),
    new CGESceneDesc('gmappers_christmas_plaza_v4_a', 'gmappers_christmas_plaza_v4_a', 'https://static.crowmonitor.com/download/maps/GMAPPERSPLAZA/gmappers_christmas_plaza_v4_a.bsp'),
    "DEMICE",
    new CGESceneDesc('demice', 'demice', 'https://static.crowmonitor.com/download/maps/DEMICE/demice.bsp'),
    new CGESceneDesc('demice_a', 'demice_a', 'https://static.crowmonitor.com/download/maps/DEMICE/demice_a.bsp'),
    new CGESceneDesc('demice_b', 'demice_b', 'https://static.crowmonitor.com/download/maps/DEMICE/demice_b.bsp'),
    new CGESceneDesc('demice_c', 'demice_c', 'https://static.crowmonitor.com/download/maps/DEMICE/demice_c.bsp'),
    new CGESceneDesc('demice_d', 'demice_d', 'https://static.crowmonitor.com/download/maps/DEMICE/demice_d.bsp'),
    new CGESceneDesc('demice_da', 'demice_da', 'https://static.crowmonitor.com/download/maps/DEMICE/demice_da.bsp'),
    new CGESceneDesc('demice_e', 'demice_e', 'https://static.crowmonitor.com/download/maps/DEMICE/demice_e.bsp'),
    new CGESceneDesc('demice_f', 'demice_f', 'https://static.crowmonitor.com/download/maps/DEMICE/demice_f.bsp'),
    new CGESceneDesc('demice_g', 'demice_g', 'https://static.crowmonitor.com/download/maps/DEMICE/demice_g.bsp'),
    new CGESceneDesc('demice_h', 'demice_h', 'https://static.crowmonitor.com/download/maps/DEMICE/demice_h.bsp'),
    "STUDIO",
    new CGESceneDesc('studio', 'studio', 'https://static.crowmonitor.com/download/maps/STUDIO/studio.bsp'),
    new CGESceneDesc('studio_a', 'studio_a', 'https://static.crowmonitor.com/download/maps/STUDIO/studio_a.bsp'),
    new CGESceneDesc('studio_c', 'studio_c', 'https://static.crowmonitor.com/download/maps/STUDIO/studio_c.bsp'),
    new CGESceneDesc('studio_ca', 'studio_ca', 'https://static.crowmonitor.com/download/maps/STUDIO/studio_ca.bsp'),
    new CGESceneDesc('studio_cb', 'studio_cb', 'https://static.crowmonitor.com/download/maps/STUDIO/studio_cb.bsp'),
    new CGESceneDesc('studio_upgrader', 'studio_upgrader', 'https://static.crowmonitor.com/download/maps/STUDIO/studio_upgrader.bsp'),
    "DOMAINS",
    new CGESceneDesc('machine', 'machine', 'https://static.crowmonitor.com/download/maps/DOMAINS/machine.bsp'),
    new CGESceneDesc('heaven', 'heaven', 'https://static.crowmonitor.com/download/maps/DOMAINS/heaven.bsp'),
    new CGESceneDesc('isolation', 'isolation', 'https://static.crowmonitor.com/download/maps/DOMAINS/isolation.bsp'),
    new CGESceneDesc('studio_explorerdomain', 'studio_explorerdomain', 'https://static.crowmonitor.com/download/maps/DOMAINS/studio_explorerdomain.bsp'),
    new CGESceneDesc('studio_creatordomain', 'studio_creatordomain', 'https://static.crowmonitor.com/download/maps/DOMAINS/studio_creatordomain.bsp'),
    new CGESceneDesc('studio_andromedadomain', 'studio_andromedadomain', 'https://static.crowmonitor.com/download/maps/DOMAINS/studio_andromedadomain.bsp'),
    new CGESceneDesc('studio_lewisdomain', 'studio_lewisdomain', 'https://static.crowmonitor.com/download/maps/DOMAINS/studio_lewisdomain.bsp'),
    "LABYRINTH",
    new CGESceneDesc('labyrinth', 'labyrinth', 'https://static.crowmonitor.com/download/maps/LABYRINTH/labyrinth.bsp'),
    new CGESceneDesc('labyrinth_a', 'labyrinth_a', 'https://static.crowmonitor.com/download/maps/LABYRINTH/labyrinth_a.bsp'),
    new CGESceneDesc('labyrinth_2', 'labyrinth_2', 'https://static.crowmonitor.com/download/maps/LABYRINTH/labyrinth_2.bsp'),
    new CGESceneDesc('labyrinth_2a', 'labyrinth_2a', 'https://static.crowmonitor.com/download/maps/LABYRINTH/labyrinth_2a.bsp'),
    new CGESceneDesc('labyrinth_3', 'labyrinth_3', 'https://static.crowmonitor.com/download/maps/LABYRINTH/labyrinth_3.bsp'),
    "NUMBERS",
    new CGESceneDesc('jeden', 'jeden', 'https://static.crowmonitor.com/download/maps/NUMBERS/jeden.bsp'),
    new CGESceneDesc('dva', 'dva', 'https://static.crowmonitor.com/download/maps/NUMBERS/dva.bsp'),
    new CGESceneDesc('tri', 'tri', 'https://static.crowmonitor.com/download/maps/NUMBERS/tri.bsp'),
    new CGESceneDesc('ctyri', 'ctyri', 'https://static.crowmonitor.com/download/maps/NUMBERS/ctyri.bsp'),
    new CGESceneDesc('five', 'five', 'https://static.crowmonitor.com/download/maps/NUMBERS/five.bsp'),
    new CGESceneDesc('sest', 'sest', 'https://static.crowmonitor.com/download/maps/NUMBERS/sest.bsp'),
    new CGESceneDesc('sedm', 'sedm', 'https://static.crowmonitor.com/download/maps/NUMBERS/sedm.bsp'),
    new CGESceneDesc('osm', 'osm', 'https://static.crowmonitor.com/download/maps/NUMBERS/osm.bsp'),
    new CGESceneDesc('osm_a', 'osm_a', 'https://static.crowmonitor.com/download/maps/NUMBERS/osm_a.bsp'),
    "HUB",
    new CGESceneDesc('hub', 'hub', 'https://static.crowmonitor.com/download/maps/HUB/hub.bsp'),
    new CGESceneDesc('hub2', 'hub2', 'https://static.crowmonitor.com/download/maps/HUB/hub2.bsp'),
    new CGESceneDesc('hub3', 'hub3', 'https://static.crowmonitor.com/download/maps/HUB/hub3.bsp'),
    new CGESceneDesc('hub4', 'hub4', 'https://static.crowmonitor.com/download/maps/HUB/hub4.bsp'),
    new CGESceneDesc('hub5', 'hub5', 'https://static.crowmonitor.com/download/maps/HUB/hub5.bsp'),
    new CGESceneDesc('hub6', 'hub6', 'https://static.crowmonitor.com/download/maps/HUB/hub6.bsp'),
    new CGESceneDesc('dm_gman', 'dm_gman', 'https://static.crowmonitor.com/download/maps/HUB/dm_gman.bsp'),
    new CGESceneDesc('banish', 'banish', 'https://static.crowmonitor.com/download/maps/HUB/banish.bsp'),
    new CGESceneDesc('death', 'death', 'https://static.crowmonitor.com/download/maps/HUB/death.bsp'),
    "REVIVAL",
    new CGESceneDesc('activator_init', 'activator_init', 'https://static.crowmonitor.com/download/maps/REVIVAL/activator_init.bsp'),
    new CGESceneDesc('activator_search', 'activator_search', 'https://static.crowmonitor.com/download/maps/REVIVAL/activator_search.bsp'),
    new CGESceneDesc('activator_environment', 'activator_environment', 'https://static.crowmonitor.com/download/maps/REVIVAL/activator_environment.bsp'),
    new CGESceneDesc('heaven_a', 'heaven_a', 'https://static.crowmonitor.com/download/maps/REVIVAL/heaven_a.bsp'),
    "BANGCLAW",
    new CGESceneDesc('rp_bangclaw', 'rp_bangclaw', 'https://static.crowmonitor.com/download/maps/BANGCLAW/rp_bangclaw.bsp'),
    "MISCELLANEOUS",
    new CGESceneDesc('yourawake', 'yourawake', 'https://static.crowmonitor.com/download/maps/TESTS/yourawake.bsp'),
    new CGESceneDesc('test_test_test', 'test_test_test', 'https://static.crowmonitor.com/download/maps/TESTS/test_test_test.bsp'),
    new CGESceneDesc('SOMBEREAGLE', 'SOMBEREAGLE', 'https://static.crowmonitor.com/download/maps/TESTS/SOMBEREAGLE.bsp'),
    new CGESceneDesc('zadny', 'zadny', 'https://static.crowmonitor.com/download/maps/TESTS/zadny.bsp'),
];

export const sceneGroup: SceneGroup = { id, name, sceneDescs };
