
import { GfxDevice } from "../gfx/platform/GfxPlatform.js";
import { SceneContext, SceneDesc, SceneGroup } from "../SceneBase.js";
import { SourceFileSystem, SourceLoadContext } from "./Main.js";
import { createScene } from "./Scenes.js";
import { createKitchenSinkSourceFilesytem } from "./Scenes_FileDrops.js";

import { CGESceneDesc } from "./Scenes_SourceDescs.js";

const id = 'CGE';
const name = 'cge7-193';
const sceneDescs = [
    "kulcs",
    new CGESceneDesc('kulcs'),
    "2fort",
    new CGESceneDesc('2fort_v1'),
    new CGESceneDesc('2fort_v2'),
    new CGESceneDesc('2fort_v3'),
    "Ask",
    new CGESceneDesc('ask_v1'),
    new CGESceneDesc('ask_v2'),
    new CGESceneDesc('ask_v3'),
    new CGESceneDesc('askask'),
    "noaccess",
    new CGESceneDesc('noaccess_v1'),
    new CGESceneDesc('noaccess_v2'),
    new CGESceneDesc('diediedie'),
    new CGESceneDesc('kurt_v1'),
    new CGESceneDesc('kurt_v2'),
    "Player Maps",
    new CGESceneDesc('funniman'),
    new CGESceneDesc('dill'),
    new CGESceneDesc('toaleken21'),
    new CGESceneDesc('dr_house'),
    "Code Maps",
    new CGESceneDesc('souer'),
    new CGESceneDesc('plotmas'),
    new CGESceneDesc('speckle'),
    new CGESceneDesc('stal'),
    new CGESceneDesc('belod'),
    new CGESceneDesc('stork'),
    new CGESceneDesc('veritas'),
    new CGESceneDesc('blemor_e'),
    new CGESceneDesc('crishy_is'),
    new CGESceneDesc('subroutine_hello'),
    "Maze",
    new CGESceneDesc('mazemazemazemaze'),
    new CGESceneDesc('coneconeconecone_v1'),
    new CGESceneDesc('coneconeconecone_v2'),
    new CGESceneDesc('coneconeconecone_anomi'),
    "Ordinance",
    new CGESceneDesc('view_v1'),
    new CGESceneDesc('view_v2'),
    new CGESceneDesc('ordinance'),
    new CGESceneDesc('ord_afunc'),
    new CGESceneDesc('ord_bfunc'),
    new CGESceneDesc('ord_cfunc'),
    new CGESceneDesc('ord_xufunc'),
    new CGESceneDesc('ord_xdfunc'),
    new CGESceneDesc('ord_yufunc'),
    new CGESceneDesc('ord_ydfunc'),
    new CGESceneDesc('ord_zufunc'),
    new CGESceneDesc('ord_zdfunc'),
    new CGESceneDesc('ord_ren'),
    new CGESceneDesc('ord_error'),
    new CGESceneDesc('ord_cry'),
    new CGESceneDesc('ord_laugh'),
    new CGESceneDesc('ord_end'),
    new CGESceneDesc('ord_play'),
    "Sacrifice Maps",
    new CGESceneDesc('vul8ty7643'),
    new CGESceneDesc('vul3sdg66'),
    new CGESceneDesc('vulhkghd'),
    "Other",
    new CGESceneDesc('hi'),
    new CGESceneDesc('the'),
    new CGESceneDesc('quiz'),
    new CGESceneDesc('verlomisquoli'),
    new CGESceneDesc('pleasekill'),
];

export const sceneGroup: SceneGroup = { id, name, sceneDescs };
